### PR TITLE
Include forked Java version in project reports

### LINKED ISSUE #112: Forked Java version not included in project info reports
### Affected version

head

### Bug description

Found by IntelliJ static analysis

### PR DESCRIPTION
**Pull request by elharo**
More excess code found by IntelliJ

fixes #112

### CODE REVIEW

File: src/main/java/org/apache/maven/report/projectinfo/SummaryReport.java [hunk 1]
```diff
@@ -148,22 +148,14 @@ private String getMinimumJavaVersion() {
             String sourceConfigured = getPluginParameter(pluginId, "source");
             String targetConfigured = getPluginParameter(pluginId, "target");
 
-            String forkFlag = getPluginParameter(pluginId, "fork");
-            String compilerVersionConfigured = null;
-            if ("true".equalsIgnoreCase(forkFlag)) {
-                compilerVersionConfigured = getPluginParameter(pluginId, "compilerVersion");
-            }
-
-            String minimumJavaVersion = compilerVersionConfigured;
```
Comment (slawekjaranowski) [inline src/main/java/org/apache/maven/report/projectinfo/SummaryReport.java:157]: Is it not needed?

Comment (elharo) [reply src/main/java/org/apache/maven/report/projectinfo/SummaryReport.java:157]: No. it's not. It's set to a different value on all three branches.

Comment (slachiewicz) [reply src/main/java/org/apache/maven/report/projectinfo/SummaryReport.java:157]: Unfortunately yes, but to me it looks like bug

Comment (elharo) [reply src/main/java/org/apache/maven/report/projectinfo/SummaryReport.java:157]: Perhaps. Do you see a case where it should be set to this?

Comment (elharo) [reply src/main/java/org/apache/maven/report/projectinfo/SummaryReport.java:157]: Maybe we should combine the ifs so 

if (targetConfigured != null)

becomes 

else if if (targetConfigured != null)

**Review by elharo — COMMENTED** [review]
PTAL

File: src/main/java/org/apache/maven/report/projectinfo/IssueManagementReport.java [hunk 2]
```diff
@@ -128,7 +128,7 @@ protected void renderBody() {
                 sink.paragraph();
                 linkPatternedText(getI18nString("scarab.intro"));
                 sink.paragraph_();
-            } else if (system == null || "".equals(system.trim())) {
+            } else if (system == null || system.trim().isEmpty()) {
```
Comment (Bukama) [inline src/main/java/org/apache/maven/report/projectinfo/IssueManagementReport.java:131]:
```suggestion
            } else if (system == null || system.isBlank()) {
```

**Review by Bukama — APPROVED** [review]
Only a small thing you could change.

File: src/main/java/org/apache/maven/report/projectinfo/IssueManagementReport.java (hunk 2 above)
Comment (slawekjaranowski) [reply src/main/java/org/apache/maven/report/projectinfo/IssueManagementReport.java:131]: `String#isBlank` ... JDK 11+
